# chart/ortelius/templates/serviceaccount.yaml (new file)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "microservice.name" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}