#!/bin/sh

if [ "$3" != "" ]; then

 mkdir $3 2>/dev/null 1>/dev/null
 chmod -R 777 $3
 cd $3
 rm -rf *
 rm -rf .git
 git clone $1 $3
 git -c advice.detachedHead=false checkout -f $2 2>&1
else
 echo Skipping checkout no target directory specified
fi
