#!/bin/sh
todir="."
branch="HEAD"

if [ "$2" != "" ]; then
 branch="$2"
fi

if [ "$3" != "" ]; then
  todir="$3"
fi

mkdir $todir 2>/dev/null 1>/dev/null
chmod -R 777 $todir
cd $todir
rm -rf *
rm -rf .git
git clone $1 $todir
git -c advice.detachedHead=false checkout -f $branch 2>&1

